# Jekyll source / destination
source:              .
destination:          ./_site/
baseurl: /notes

defaults:
  
  # all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
  # all _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: true
      read_time: true
      comments: true
      share: true


plugins: 
# - 'jekyll-lunr-js-search' [UNSUPPORTED] 
 - 'jekyll-seo-tag' # setting in seo.yml
 - 'jekyll/responsive_image' # settings in responsive_image.yml
 - 'jekyll-redirect-from' # https://github.com/jekyll/jekyll-redirect-from
 - 'jekyll-paginate-v2' # https://github.com/sverrirs/jekyll-paginate-v2
