# Blog settings
permalink: '/archive/:year/:month/:slug.html'
limit_posts: 0
searchindex: yes
#url: /home/tom/blog/_site/
#url: http://127.0.0.1:4000/
url: https://tomasparks.github.io/
#url: /
keep_files:   [".git"]
include: [".htaccess"]
exclude: ["README.md", "LICENSE","build.sh","Gemfile.lock","Gemfile"]
name: Tom Sparks
description: 
google_verification: null




gems: 
 - 'jekyll-pandoc-multiple-formats'
 - 'jekyll-lunr-js-search'
 - 'jekyll-seo-tag'
 - 'jekyll-picture-tag'



markdown: pandoc
pandoc:
#    skip: false
# bundle_permalink: '/:slug.:output_ext'
#   papersize: 'a4paper'
#   sheetsize: 'a4paper'
#    imposition: true
#    binder: true
#    flags: '--smart'
    site_flags: ' --smart --toc --atx-headers'
#    outputs:
#      pdf: '--latex-engine=pdflatex'
#      epub: '--epub-chapter-level=2'


picture:
  source: "images/_originals"
  output: "images"
  posts_folders: ":year/:month/:slug/"
  markup: "picture"
  presets:
    default:
      attr:
        class: "page-image"
        itemprop: "image"
      ppi: [1]
      source_1600:
        media: "(min-width: 1600px)"
        width: "1600"
      source_1024:
        media: "(min-width: 1024px)"
        width: "1024"
      source_768:
        media: "(min-width: 768px)"
        width: "768"
      source_600:
        media: "(min-width: 600px)"
        width: "600"
      source_default:
        width: "320"




lunr_search:
  js_dir: "./assets/js/"
  excludes: [rss.xml, 404.html]



citation:
#    citation_style: apa
#    citation_locale: en



# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
#markdown: kramdown
#kramdown:
#  input: GFM
#  hard_wrap: false
#highlighter: rouge


collections:
  reviews:
    layout: page
    output: true
    permalink: /reviews/:path/
  questions:
    layout: page
    output: true
    permalink: /questions/:path/
