# Blog settings
permalink: '/archive/:year/:month/:slug.html'
limit_posts: 0
searchindex: yes
#url: /home/tom/blog/_site/
#url: http://127.0.0.1:4000/
url: https://tomasparks.github.io/
#url: /
keep_files:   [".git"]
include: [".htaccess"]
exclude: ["README.md", "LICENSE","build.sh","Gemfile.lock","Gemfile"]
name: Tom Sparks
description: 
google_verification: null




gems: 
 - 'jekyll-pandoc-multiple-formats'
 - 'jekyll-lunr-js-search'
 - 'jekyll-seo-tag'
 - 'jekyll/responsive_image'
 - 'jekyll-gallery-generator'



markdown: pandoc
pandoc:
#    skip: false
# bundle_permalink: '/:slug.:output_ext'
#   papersize: 'a4paper'
#   sheetsize: 'a4paper'
#    imposition: true
#    binder: true
#    flags: '--smart'
    site_flags: ' --smart --toc --atx-headers'
#    outputs:
#      pdf: '--latex-engine=pdflatex'
#      epub: '--epub-chapter-level=2'


responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 95

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 160  # [Required] How wide the resized image will be.
  #    quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 320
    - width: 640
    - width: 800
    - width: 1024
    - width: 1920


  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets/img/_originals/

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/img/resized/%{width}/%{basename}

  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
   - assets/img/_originals/*.png
   - assets/img/_originals/*.jpg


lunr_search:
  js_dir: "./assets/js/"
  excludes: [rss.xml, 404.html]



citation:
#    citation_style: apa
#    citation_locale: en



# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
#markdown: kramdown
#kramdown:
#  input: GFM
#  hard_wrap: false
#highlighter: rouge


collections:
  reviews:
    layout: page
    output: true
    permalink: /reviews/:path/
  questions:
    layout: page
    output: true
    permalink: /questions/:path/



gallery:
  dir: art               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Artwork"           # Title for gallery index page
  title_prefix: "Artwork: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "title"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    chile_trip:
      best_image: IMG_1068.JPG  # The image to show on the gallery index page. Defaults to the last image.
    japan_trip:
      best_image: IMG_0690.JPG
      name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
    awesome_stuff:
      best_image: snaileo_gonzales.jpg
      sort_reverse: true    # Reverse sort images in gallery.
    secret_stuff:
      hidden: true          # Don't show this gallery on the index page. People must guess the URL.
