# Blog settings
permalink: '/archive/:year/:month/:slug.html'

#url: /home/tom/blog/_site/
#url: http://127.0.0.1:4000/
url: https://tomasparks.github.io/
#url: /home/tom/github/blog/tomasparks.github.io/
#url: /
keep_files:   [".git"]
include: [".htaccess"]
exclude: ["README.md", "LICENSE","build.sh","Gemfile.lock","Gemfile"]

strict_front_matter: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge


collections:
   components:
    output: false
   colors:
    output: false
   projects:
     output: true
     permalink: /projects/:name.html
#  computers:
#    layout: page
#    output: true
#    permalink: /about-me/computers/:name.html
#  questions:
#    layout: page
#    output: true
#    permalink: /questions/:path/


plugins: 
# - 'jekyll-pandoc'
# - 'jekyll-lunr-js-search'
 - 'jekyll-seo-tag'
 - 'jekyll/responsive_image'
# - 'jekyll-redirect-from'
# - 'jekyll-paginate-v2'
# - 'jekyll/scholar'
# - 'jekyll/scholar/extras'
# - 'jekyll-pandoc-multiple-formats'

