# Blog settings
permalink: '/archive/:year/:month/:slug.html'

limit_posts: 0
searchindex: yes
#url: /home/tom/blog/_site/
#url: http://127.0.0.1:4000/
#url: https://tomasparks.github.io/
url: /home/tom/github/blog/tomasparks.github.io/
#url: /
keep_files:   [".git"]
include: [".htaccess"]
exclude: ["README.md", "LICENSE","build.sh","Gemfile.lock","Gemfile"]
name: Tom Sparks
description: 
google_verification: null


repository               : "tomasparks/website"
branch: "master"


# reCAPTCHA keys
reCaptcha:
  siteKey: "6LfK3S0UAAAAAN8Vg2RId7K8Aq8y-RtRevo6Bgfv"
  secret: "6LfK3S0UAAAAAKe4pOV4fkqpdARWDrQ5xcyNML8R"


plugins: 
 - 'jekyll-pandoc'
 - 'jekyll-lunr-js-search'
 - 'jekyll-seo-tag'
 - 'jekyll/responsive_image'
 - 'jekyll-redirect-from'
 - 'jekyll-paginate-v2'
# - 'jekyll-pandoc-multiple-formats'



markdown: Pandoc
pandoc:
  extensions:
    - smart
    - toc
    - atx-headers



############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 1

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

############################################################

############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: false

  # Category pages, omit entire config element to disable
  categories: 
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts: 
      - 'autopage_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced), 
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/archive/category/:cat'

  # Collection pages, omit to disable
  collections:
    layouts: 
      - 'autopage_collection.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    permalink: ':coll'
  
  # Tag pages, omit to disable
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/archive/tag/:tag'




responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 95

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
  #  - width: 160  # [Required] How wide the resized image will be.
  #    quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 320
    - width: 640
    - width: 800
    - width: 1024
    - width: 1920


  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: /\assets/img/_originals/

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/img/resized/%{width}/%{basename}

  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
   - assets/img/_originals/*.png
   - assets/img/_originals/*.jpg


lunr_search:
  js_dir: "./assets/js/"
  excludes: [rss.xml, 404.html,.schematic]



citation:
#    citation_style: apa
#    citation_locale: en



# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
#markdown: kramdown
#kramdown:
#  input: GFM
#  hard_wrap: false
#highlighter: rouge


collections:
   components:
    output: false
   colors:
    output: false
   projects:
     output: true
     permalink: /projects/:name.html
#  computers:
#    layout: page
#    output: true
#    permalink: /about-me/computers/:name.html
#  questions:
#    layout: page
#    output: true
#    permalink: /questions/:path/

album_dir: art
source_dir: art

strict_front_matter: true

