# Blog settings
permalink: '/archive/:year/:month/:slug.html'
limit_posts: 0
searchindex: yes
#url: /home/tom/blog/_site/
#url: http://127.0.0.1:4000/
url: https://tomasparks.github.io/
#url: /
keep_files:   [".git"]
include: [".htaccess"]
exclude: ["README.md", "LICENSE","build.sh","Gemfile.lock","Gemfile"]
name: Tom Sparks
description: 
google_verification: null


repository               : "tomasparks/website"

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LfK3S0UAAAAAN8Vg2RId7K8Aq8y-RtRevo6Bgfv"
  secret: "6LfK3S0UAAAAAKe4pOV4fkqpdARWDrQ5xcyNML8R"


gems: 
 - 'jekyll-pandoc'
 - 'jekyll-lunr-js-search'
 - 'jekyll-seo-tag'
 - 'jekyll/responsive_image'
 - 'jekyll-redirect-from'



markdown: Pandoc
pandoc:
  extensions:
    - smart
    - toc
    - atx-headers



responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 95

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
  #  - width: 160  # [Required] How wide the resized image will be.
  #    quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 320
    - width: 640
    - width: 800
    - width: 1024
    - width: 1920


  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: /\assets/img/_originals/

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/img/resized/%{width}/%{basename}

  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
   - assets/img/_originals/*.png
   - assets/img/_originals/*.jpg


lunr_search:
  js_dir: "./assets/js/"
  excludes: [rss.xml, 404.html,.schematic]



citation:
#    citation_style: apa
#    citation_locale: en



# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
#markdown: kramdown
#kramdown:
#  input: GFM
#  hard_wrap: false
#highlighter: rouge


collections:
  minecraft:
    layout: page
    output: true
    permalink: /projects/minecraft/:name.html
  X3D:
    layout: page
    output: true
    permalink: /projects/X3D/:name.html
  lego:
    layout: page
    output: true
    permalink: /projects/lego/:name.html
  computers:
    layout: page
    output: true
    permalink: /about-me/computers/:name.html
  questions:
    layout: page
    output: true
    permalink: /questions/:path/

album_dir: art
source_dir: art
