# GitHub
username:             tomasparks
repo:                 website
repo_branch:          master
dest_repo:            tomasparks.github.io
dest_branch:          master

# Jekyll source / destination
source:               .
destination:          _site


# Blog settings
permalink: '/archive/:year/:month/:slug.html'

keep_files:   [".git"]
include: [".htaccess"]
exclude: ["README.md", "LICENSE","Gemfile.lock","Gemfile","*.yml"]

strict_front_matter: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge




plugins: 
# - 'jekyll-lunr-js-search' [UNSUPPORTED] 
 - 'jekyll-seo-tag' # setting in seo.yml
 - 'jekyll/responsive_image' # settings in responsive_image.yml
 - 'jekyll-redirect-from' # https://github.com/jekyll/jekyll-redirect-from
# - 'jekyll-paginate-v2' # https://github.com/sverrirs/jekyll-paginate-v2
 - 'jekyll/scholar' # settings in scholar.yml
# - 'jekyll/scholar/extras' # settings in scholar.yml
 - 'jekyll-last-modified-at'
 - 'jekyll-webmention_io' # setting in webmentions.yml
