# Blog settings
permalink: /:categories/:year/:month/:day/:slug.html
limit_posts: 0
searchindex: yes
#url: /home/tom/blog/_site/
#url: http://127.0.0.1:4000/
url: https://tomasparks.github.io/
#url: /
keep_files:   [".git", ".svn",".sh"]


lunr_search:
  js_dir: "./assets/js/"
  excludes: [rss.xml, 404.html]

gems:      []

gems: [ 'jekyll-pandoc-multiple-formats' ]
markdown: pandoc
pandoc:
#    skip: false
# bundle_permalink: '/:slug.:output_ext'
#   papersize: 'a4paper'
#   sheetsize: 'a4paper'
#    imposition: true
#    binder: true
#    flags: '--smart'
    site_flags: ' --smart --toc --atx-headers'
#    outputs:
#      pdf: '--latex-engine=pdflatex'
#      epub: '--epub-chapter-level=2'

citation:
    citation_style: apa
    citation_locale: en

# My variables
name: Tom Sparks
description: 
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
#markdown: kramdown
#kramdown:
#  input: GFM
#  hard_wrap: false
#highlighter: rouge
