source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-lunr-js-search'
#gem 'jekyll-archives'
gem 'jekyll-seo-tag'
#gem 'jekyll-feed'
gem 'rmagick'
gem 'exifr'
gem'jekyll-assets'

#gem 'rmagick'
#gem 'jekyll-responsive_image'
#gem 'jekyll-picture-tag', github: 'nhoizey/jekyll-picture-tag'
gem 'jekyll-responsive_image' 

gem 'html-proofer'
#gem 'jekyll-pandoc-multiple-formats', github: 'edsl/jekyll-pandoc-multiple-formats', branch: 'develop'
gem 'jekyll-pandoc-multiple-formats', :path => '~/src/jekyll-pandoc-multiple-formats/'

gem 'pdf_info'
gem 'rtex'
