source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-lunr-js-search'
#gem 'jekyll-archives'
gem 'jekyll-seo-tag'
#gem 'jekyll-feed'
#gem 'rmagick'
#gem 'exifr'
gem'jekyll-assets'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate-v2'
gem 'jekyll-scholar'
#gem 'jekyll-scholar-extra'
gem 'jekyll-webmention_io'
#gem 'rmagick'
gem 'jekyll-responsive_image'
#gem 'jekyll-picture-tag', github: 'nhoizey/jekyll-picture-tag'
gem 'jekyll-last-modified-at'
gem 'rake'
#gem 'html-proofer'

#gem 'jekyll-pandoc-multiple-formats'
#gem 'jekyll-pandoc-multiple-formats', github: 'tomasparks/jekyll-pandoc-multiple-formats'
#gem 'jekyll-pandoc-multiple-formats', :path => '~/src/jekyll-pandoc-multiple-formats/'
gem 'jekyll-pandoc'
gem 'pandoc-ruby'

gem 'jekyll-asciinema'

#gem 'pdf_info'
#gem 'rtex'
