page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'member'
    template: 'profile'
    name: 'full_name'
    dir: 'people'
  - data: 'pet'
    template: 'profile'
    name: 'full_name'
    dir: 'pets'
